server:
  port: 8080
token:
  refreshTime: 10L
  expiresTime: 10L
  secretKey: jwt_secret

spring:
  datasource:
    url: jdbc:mysql://106.13.236.41:10028/labmanage
    username: root
#    password: 123456
    password: labmanageDatabase

#    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: localhost
    password: PGg5C:sBEnH4.jZ


logging:
  level:
    com.example: debug


# 写了下面这一段,mybstis就会自动帮我们判断有没有逻辑删除啦,不用自己动手写那么麻烦
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted # 用deleted来表示数据有没有被删除
      logic-not-delete-value: 0  # 0表示没有删除
      logic-delete-value: 1 # 1 表示已经删除
