name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Spring Boot project
        run: mvn -B package --file pom.xml
        env:
          JAVA_HOME: ${{ env.JDK_17 }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/labmanageback:${{ github.sha }}

  deploy:
    name: Deploy Docker image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH into server
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/labmanageback:${{ github.sha }}
      - name: Stop and remove old container
        run: docker stop labmanageback || true && docker rm labmanageback || true
      - name: Run Docker container
        run: docker run -d --name labmanageback -p 10026:8080 ${{ secrets.DOCKER_USERNAME }}/labmanageback:${{ github.sha }}

