name: Build and Deploy

on:
  push:
    branches:
      - ZC0

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build Spring Boot project
        run: mvn -B package --file pom.xml
        env:
          JAVA_HOME: ${{ env.JDK_8 }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.7.0

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/labmanageback:${{ github.sha }}

  deploy:
    name: Deploy Docker image
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: SSH to server and update Docker container
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.IP_ADDRESS }}
        username: ${{ secrets.SERVER_NAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/labmanageback:${{ github.sha }}
          docker stop labmanageback || true && docker rm labmanageback || true
          docker run -d --name labmanageback -p 10026:8080 ${{ secrets.DOCKER_USERNAME }}/labmanageback:${{ github.sha }}
